// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9JTermVDTdVZF5ZShb7ZA1FznVBdYCj4',
    appId: '1:376970264343:web:1921a78f6a24bcc4628152',
    messagingSenderId: '376970264343',
    projectId: 'bolaodogamma-v0',
    authDomain: 'bolaodogamma-v0.firebaseapp.com',
    storageBucket: 'bolaodogamma-v0.firebasestorage.app',
    measurementId: 'G-PN06ZD55LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA06-g6a4qDGV8X2GzcnXgLygX37r7JLg',
    appId: '1:376970264343:android:c48c29c777bd0fc8628152',
    messagingSenderId: '376970264343',
    projectId: 'bolaodogamma-v0',
    storageBucket: 'bolaodogamma-v0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvl-rrlbvUiX6NZRKJ86eiTsTTWcV-i7U',
    appId: '1:376970264343:ios:afd29917dc10aa36628152',
    messagingSenderId: '376970264343',
    projectId: 'bolaodogamma-v0',
    storageBucket: 'bolaodogamma-v0.firebasestorage.app',
    iosBundleId: 'com.example.bolaodogammaV0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvl-rrlbvUiX6NZRKJ86eiTsTTWcV-i7U',
    appId: '1:376970264343:ios:afd29917dc10aa36628152',
    messagingSenderId: '376970264343',
    projectId: 'bolaodogamma-v0',
    storageBucket: 'bolaodogamma-v0.firebasestorage.app',
    iosBundleId: 'com.example.bolaodogammaV0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9JTermVDTdVZF5ZShb7ZA1FznVBdYCj4',
    appId: '1:376970264343:web:a9842401681ed0e2628152',
    messagingSenderId: '376970264343',
    projectId: 'bolaodogamma-v0',
    authDomain: 'bolaodogamma-v0.firebaseapp.com',
    storageBucket: 'bolaodogamma-v0.firebasestorage.app',
    measurementId: 'G-MHJCLD9922',
  );
}
